$(function() {
  blacklist = ["100percentfedup.com",
  "enduringvision.com",
  "pakalertpress.com",
  "21stcenturywire.com",
  "fprnradio.com",
  "politicalblindspot.com",
  "70news.wordpress.com",
  "the free thought project",
  "politicalears.com",
  "abcnews.com.co",
  "geoengineeringwatch.org",
  "politicalo",
  "activistpost.com",
  "globalresearch.ca",
  "politicususa",
  "addicting info",
  "govtslaves.info",
  "prisonplanet.com",
  "american news x",
  "gulagbound.com",
  "prisonplanet.tv",
  "americannews.com",
  "hangthebankers.com",
  "private-eye.co.uk ",
  "anonnews.co",
  "humansarefree.com",
  "projectveritas",
  "associated media coverage",
  "huzlers",
  "rawstory",
  "beforeitsnews.com",
  "ifyouonlynews",
  "react 365",
  "being liberal",
  "indecision forever ",
  "realfarmacy.com",
  "bigamericannews.com",
  "ijr ",
  "realnewsrightnow.com",
  "bigpzone.com",
  "infowars",
  "redflagnews.com",
  "bipartisan report",
  "infowars.com",
  "red state",
  "bizpac review",
  "intellihub.com",
  "reductress ",
  "blue nation review",
  "inquisitor.com ",
  "rilenews.com",
  "breitbart",
  "jonesreport.com",
  "satira tribune",
  "cap news  ",
  "lewrockwell.com",
  "sprotspickle.com",
  "christwire.org ",
  "liberal america",
  "the blaze",
  "chronicle.su",
  "libertytalk.fm",
  "the free thought project",
  "civictribune.com",
  "libertyunyielding ",
  "the new yorker’s borowitz report ",
  "clickhole.com ",
  "libertyvideos.org",
  "the onion ",
  "coasttocoastam.com",
  "lmr ",
  "the other 98%",
  "collectiveevolution",
  "mediamass.net",
  "the reporterz",
  "consciouslifenews.com",
  "megynkelly.us",
  "the stately harold",
  "conservativeoutfitters.com",
  "msnbc.com.co",
  "thedailysheeple.com",
  "conspiracywire ",
  "msnbc.website",
  "thenewsnerd.com",
  "countdowntozerotime.com",
  "naha daily",
  "therundownlive.com",
  "counterpsyops.com",
  "national report",
  "theuspatriot.com",
  "creambmp.com",
  "nationalreport.net",
  "thinkprogress.org",
  "crooks and liars",
  "naturalnews.com",
  "truthfrequencyradio.com",
  "dailybuzzlive.com",
  "nc scooper",
  "twitchy.com",
  "dailycurrant.com",
  "nct ",
  "unconfirmedsources.com",
  "daily newsbin",
  "news examiner",
  "upworthy ",
  "daily wire",
  "news-hound.com",
  "usa supreme",
  "dcclothesline.com",
  "newsbiscuit.com",
  "us.blasting.news",
  "dcgazette.com",
  "newsbuzzdaily",
  "us uncut",
  "derfmagazine.com",
  "newslo",
  "veteranstoday.com",
  "disclose.tv",
  "newsmutiny.com",
  "walking times",
  "drudgereport.com.co",
  "newswatch 28",
  "wakingupwisconsin.com",
  "duffleblog.com ",
  "newswatch 33",
  "winning democrats",
  "duhprogressive.com",
  "newswire-24.com",
  "witscience.org",
  "embols.com",
  "nodisinfo.com",
  "world net daily",
  "empire herald",
  "now8news",
  "world news daily report",
  "empire news",
  "nowtheendbegins.com",
  "worldtruth.tv",
  "empirenews.com",
  "occupy democrats",
  "zerohedge",
  "endingthefed.com"]
  $("a").each(function() {
    link = $(this);
    href = $(this).attr("href");
    $.each(blacklist, function(i, value) {
      if (new RegExp(value).test(href)) {
        link.css("color", "red");
      }
    });
  });
});
